application: google.com:bowerarchiver
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"

handlers:

- url: /
  static_files: static/index.html
  upload: static/index\.html
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /bower_components
  static_dir: static/bower_components
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /elements
  static_dir: static/elements
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /archive
  script: main.app

#- url: .*
#  script: main.app
